services:
  postgres_deck:
    container_name: postgres_deck
    image: postgres:17
    environment:
      POSTGRES_USER: serviceuser
      POSTGRES_PASSWORD: servicepwd
      POSTGRES_DB: deck
    ports:
      - "5432:5432"
    volumes:
      - deck_data:/var/lib/postgresql/data
    networks:
      - m2026

  postgres_resolver:
    container_name: postgres_resolver
    image: postgres:17
    environment:
      POSTGRES_USER: serviceuser
      POSTGRES_PASSWORD: servicepwd
      POSTGRES_DB: resolver
    ports:
      - "5433:5432"
    volumes:
      - resolver_data:/var/lib/postgresql/data
    networks:
      - m2026


  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_LISTENERS: CONTROLLER://:9091,HOST://:9092,DOCKER://:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - m2026

  consul:
    image: hashicorp/consul:2.0.0
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command:
      agent -dev -node=m26 -client=0.0.0.0
    networks:
      - m2026

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - m2026

  deck:
    image: deck:0.0.1-SNAPSHOT
    container_name: deck
    build:
      context: ./deck
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "optional:consul:"
      SPRING_CLOUD_CONSUL_HOST: "consul"
    depends_on:
      - consul
      - postgres_deck
    ports:
      - "8001:8001"
    networks:
      - m2026

  resolver:
    image: resolver:0.0.1-SNAPSHOT
    container_name: resolver
    build:
      context: ./resolver
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "optional:consul:"
      SPRING_CLOUD_CONSUL_HOST: "consul"
    depends_on:
      - deck
    ports:
      - "8006:8006"
    networks:
      - m2026

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    container_name: gateway
    build:
      context: ./gateway
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "optional:consul:"
      SPRING_CLOUD_CONSUL_HOST: "consul"
    depends_on:
      - consul
    ports:
      - "8100:8100"
    networks:
      - m2026

  round:
    image: round:0.0.1-SNAPSHOT
    container_name: round
    build:
      context: ./round
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "optional:consul:"
      SPRING_CLOUD_CONSUL_HOST: "consul"
    depends_on:
      - consul
    ports:
      - "8000:8000"
    networks:
      - m2026



networks:
  m2026:
    name: m2026
    driver: bridge

volumes:
  deck_data:
  resolver_data: