# Build step
FROM maven:3.9.4-eclipse-temurin-21 AS build
WORKDIR  /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Run step
FROM eclipse-temurin:21-alpine
COPY ./target/deck-0.0.1-SNAPSHOT.jar /usr/src/deck/
WORKDIR /usr/src/deck/
EXPOSE 8001
CMD ["java", "-jar", "deck-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=docker"]