spring.application.name=mono

server.port=8000

# H2 database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 web console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Deck
# deck.service.url=http://localhost:8001/api/deck/cards
deck.service.url=http://deck:8001/api/deck/cards

logging.level.root=WARN
logging.level.org.hibernate=ERROR

# Kafka
spring.kafka.bootstrap-servers=kafka:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false